name = "ImageGeoms"
uuid = "9ee76f2b-840d-4475-b6d6-e485c9297852"
authors = ["Jeff Fessler <fessler@umich.edu>"]
version = "0.2.0"

[deps]
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
LazyGrids = "7031d0ef-c40d-4431-b2f8-61a8d2f650db"

[compat]
FillArrays = "0.12"
LazyGrids = "0.2.0"
julia = "1.6"